•Out "Hello World"

A ← 1 # comment
BB ← 2   # comment
CCC ← 3 # comment
DDDD  ← 4 # comment

BBx ← 2   # comment
CCCx ← 3 # comment
DDDDx  ← 4 # commen

BBxx ← 2   # comment
CCCxx ← 3 # comment
DDDDDDxx   ←4 + t ← 10 # comment

FunctionWithALongerName ← {
    A ← 1 # comment
    BB ← 2   # comment
    CCC ← 3 # comment
    DDDD  ← 4 # comment
    "do something extra"∾t←"other stuff"
}

A ← { 𝕩 }
BB ← { 𝕩 }
CCC ← { 𝕩 }
